import Dock from "./components/Dock/Dock";
import Header from "./components/Header";
import "./globals.css";
import { Exo_2 } from "next/font/google";

const Exo2 = Exo_2({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${Exo2.className} flex overflow-hidden`}>
				{children}
				<Header />
				<Dock />
			</body>
		</html>
	);
}
